### ISSUE TITLE
BattleTags vs HeroIDs

### ISSUE THREAD

**Issue by jnovack** [ebshimizu/hots-parser#1]
Blizzard REALLY doesn't like applications using BattleTags for a number of reasons:

1. It is not unique.
2. It can change.
3. It enables the ability to 'harass' a player (adding as a friend, whisper, etc), when they otherwise would not know this information.

Because of that, the HeroProtocol.JS library specifically does not extract them (which, I'm sure, is why you made `battletags.js`).

I return the player information (sans `#{4-10}` ID number) under the `replay.details` file in the format below.  The Region+Realm+ID is enough to be globally unique.

```
{
  "m_playerList": [
  {
      "m_name": "OreoChsCake",
      "m_toon": {
        "m_region": 1,
        "m_programId": "Hero",
        "m_realm": 1,
        "m_id": 5795634
      },
      "m_race": " ",
      "m_color": {
        "m_a": 255,
        "m_r": 255,
        "m_g": 0,
        "m_b": 0
      },
      "m_control": 2,
      "m_teamId": 1,
      "m_handicap": 0,
      "m_observe": 0,
      "m_result": 1,
      "m_workingSetSlotId": 7,
      "m_hero": "Malfurion"
    }
  ,...
  ]
}
```

This is merely an informational post, I can see that there are some application changes required as well, this is just logging the issue in hopes we can get to it. :)

**Comment by ebshimizu** [comment]
yeah i think we've talked a bit. Can add an option to not return battletags, though I plan to leave the functionality in it to maintain parity with the C# parser that's out there.

**Comment by jnovack** [comment]
At the very least, I can at least return the file through the library (as binary, since it cannot be decoded), so, you at least do not have to rely on downloading 4 libraries for a single file and purpose.

**Comment by jnovack** [comment]
`heroprotocol@2.0.0-alpha.2` passes back unparsed files (such as `replay.server.battlelobby` as a buffer.

This should remove the reliance on `empeeku` within this module.

**Comment by ebshimizu** [comment]
awesome! I'll check it out. I will wait until `heroprotocol-2.0.0` is out of alpha before pushing along that particular update to my app.

**Comment by jnovack** [comment]
can you at least test it?  you are the only person using the software that I'm in contact with at this time.

The FaaS parser works, I just need to make sure the desktop works in windows.

**Comment by ebshimizu** [comment]
Yep I'll test it out. Will add an update here once I have time to run a few tests.

**Comment by ebshimizu** [comment]
Tried to use 2.0.0-alpha.3 as a drop in replacement. Got an error. Details below. Possibly missing a module?

System: Windows 10 x64, process running under electron 2.0.3.

The following was preceded by `C:\Users\falindrith\Dropbox\Documents\side_projects\hots-analysis\node_modules\heroprotocol\index.js:120 heroprotocol.js is using Javascript extraction, which is notably slower and will be re-written in the future. See README.md for more details.`

```
"ReferenceError: filename is not defined
    at Object.exports.extractFileJS (C:\Users\falindrith\Dropbox\Documents\side_projects\hots-analysis\node_modules\heroprotocol\index.js:141:38)
    at Object.exports.get (C:\Users\falindrith\Dropbox\Documents\side_projects\hots-analysis\node_modules\heroprotocol\index.js:121:20)
    at parse (C:\Users\falindrith\Dropbox\Documents\side_projects\hots-analysis\hots-parser\parser.js:64:45)
    at Object.getHeader (C:\Users\falindrith\Dropbox\Documents\side_projects\hots-analysis\hots-parser\parser.js:86:16)
    at Database.checkDuplicate (C:\Users\falindrith\Dropbox\Documents\side_projects\hots-analysis\js\database.js:389:25)
    at parseReplaysAsync (file:///C:/Users/falindrith/Dropbox/Documents/side_projects/hots-analysis/js/settings.js:493:6)
    at HTMLDivElement.parseReplays (file:///C:/Users/falindrith/Dropbox/Documents/side_projects/hots-analysis/js/settings.js:448:5)
    at HTMLDivElement.dispatch (C:\Users\falindrith\Dropbox\Documents\side_projects\hots-analysis\node_modules\jquery\dist\jquery.js:5183:27)
    at HTMLDivElement.elemData.handle (C:\Users\falindrith\Dropbox\Documents\side_projects\hots-analysis\node_modules\jquery\dist\jquery.js:4991:28)"
```
